### ISSUE TITLE
OpenMined Courses website is crashing

### ISSUE THREAD

**Issue by POONAM2015** [OpenMined/openmined#221] opened 2022-11-15 13:05 UTC
## Description
The site https://courses.openmined.org/ keeps getting crashed as soon as I access it.

## How to Reproduce
1. Go to https://courses.openmined.org/
2. Wait for a few seconds (not more than 5 seconds in my case)
3. If the site does not crash - go to "courses" tab (https://courses.openmined.org/courses). Now it will definitely crash.

## Expected Behavior
Site should not crash.

## Screenshots
![image](https://user-images.githubusercontent.com/11383559/201925820-7d6dda1a-e488-49a5-a898-d7f1cf1d47ed.png)
![image](https://user-images.githubusercontent.com/11383559/201926131-a1896121-f96a-4498-ada9-d8bcc6f5ab6b.png)

## System Information
 - OS: Windows 10
 - OS Version: 21H2
 - Browser (if applicable): Firefox and Edge
 - Browser Version (if applicable): Firefox 106.0.5 (64-bit) and Edge 107.0.1418.42 (Official build) (64-bit)

**Comment by sumitgiri87** [comment] 2022-11-15 14:54
Same with me. Seems to be an issue with everyone.

**Comment by gaurishg** [comment] 2022-11-15 16:04
Yes, not working for me also.

**Comment by madhavajay** [comment] 2022-11-16 02:46
@POONAM2015 thank you for reporting this. I can confirm its down and we are looking into it.

**Comment by madhavajay** [comment] 2022-11-16 07:06
This should be fixed, please refresh and try again. 🙏

**Closed as completed by madhavajay** 2022-11-16 07:06 UTC
Labels: Type: Bug :bug:
